import Head from 'next/head'

// Valentín Galfré template for NextJS + TailwindCSS Project (with Poppins font)
// Just type NPM I, then NPM RUN DEV


export default function Home() {
  return (
    <div>
      <Head>
        <title>Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <div className='p-6' >
        <h1 className='text-3xl font-bold bg-slate-300 text-white' >Change me!</h1>
        <p>Template by Valentin Galfre</p>
      </div>


      


    </div>
  )
}
